name: Update Changelog

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Generate changelog
        run: npx auto-changelog --output CHANGELOG.rst --hide-credit

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert MD to RST
        run: pandoc -f markdown -t rst -o CHANGELOG.rst CHANGELOG.rst

      - uses: stefanzweifel/git-auto-commit-action@v5
