name: Update Changelog

on:
  push:
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install auto-changelog
        run: npm install -g auto-changelog

      - name: Generate changelog
        run: auto-changelog --output CHANGELOG.rst

      - uses: stefanzweifel/git-auto-commit-action@v5
